version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: |
            gem install bundler:2.2.27
            bundle -v
      - ruby/bundle-install
